"""Emit an immutable plan and an executable OpenFHE-Python entry script."""

from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path

from autohe_prs.config import FHEPlan


SCRIPT = '''\
#!/usr/bin/env python3
"""Generated by AutoHE-PRS. Do not edit; regenerate from the plan."""
from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path

from autohe_prs.config import Constraints, FHEPlan
from autohe_prs.fhe.runner import run_openfhe_plan
from autohe_prs.genomics.io import read_harmonized

PLAN = FHEPlan(**{plan})
CONSTRAINTS = Constraints(**{constraints})


def main() -> int:
    # The OpenFHE adapter performs: parameter/context setup, feature enable,
    # key and evaluation-key generation, encoding, encryption, MulPlain,
    # slot reduction, chunk aggregation, decryption/decoding, serialization,
    # and plaintext error comparison. Failed stages become explicit records.
    _, dosages, weights = read_harmonized({dosage_path!r}, {weight_path!r})
    result = run_openfhe_plan(PLAN, dosages, weights, constraints=CONSTRAINTS)
    print(json.dumps(asdict(result), indent=2, sort_keys=True))
    return 0 if result.status == "ok" else 2


if __name__ == "__main__":
    raise SystemExit(main())
'''


def emit(
    plan: FHEPlan,
    output_script: str | Path,
    *,
    constraints: dict | None = None,
    dosage_path: str = "data/harmonized/dosage.csv",
    weight_path: str = "data/harmonized/weights.csv",
) -> tuple[Path, Path]:
    script_path = Path(output_script)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    config_path = script_path.with_suffix(".plan.json")
    config_path.write_text(
        json.dumps(asdict(plan), indent=2, sort_keys=True), encoding="utf-8"
    )
    portable_dosage_path = Path(dosage_path).as_posix()
    portable_weight_path = Path(weight_path).as_posix()
    script_path.write_text(
        SCRIPT.format(
            plan=repr(asdict(plan)),
            constraints=repr(constraints or {}),
            dosage_path=portable_dosage_path,
            weight_path=portable_weight_path,
        ),
        encoding="utf-8",
    )
    return config_path, script_path
